baseURL = 'https://praneetshekhar.github.io/'
languageCode = 'en-in'
title = 'OutOfBounds'
theme = 'hugo-PaperMod'
enableEmoji = true

[params.homeInfoParams]
Title = "Hi there :waving_hand:"
Content = "I am Praneet Shekhar."

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/praneetshekhar/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/praneetshekhar"

[[params.socialIcons]]
name = "WhatsApp"
url = "https://wa.me/917209155651"

[params]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
disableScrollToTop = false
siteCopyright = 'Praneet Shekhar'
name = '010100000111001001100001011011100110010101100101011101000010000001010011011010000110010101101011011010000110000101110010'

[params.assets]
favicon = "/images/favicon.ico"

[params.profileMode]
enabled = true
title = "Hi there :waving_hand:"
subtitle = "I am Praneet, this is my home on the web."
imageUrl = "/images/faceshot-profile-pic.jpg"
imageTitle = ""
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Resume"
url = "/praneet-shekhar_resume.pdf"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/praneet-shekhar_resume.pdf"
weight = 3
